import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { generateRoadmapFromPrompt } from '../../lib/services/aiRoadmapGenerator';
import { WizardStepSkill } from './WizardStepSkill';
import { WizardStepDuration } from './WizardStepDuration';
import { WizardStepPreferences } from './WizardStepPreferences';
import { WizardStepLoading } from './WizardStepLoading';

interface CreationWizardProps {
  onClose: () => void;
  onComplete: (roadmapId: string) => void;
  initialSkill?: string;
}

export interface WizardState {
  skill: string;
  durationWeeks: number;
  dailyMinutes: number;
  experienceLevel: string;
  learningPreferences: string[];
  goalStatement: string;
}

export function CreationWizard({ onClose, onComplete, initialSkill = '' }: CreationWizardProps) {
  const { dispatch } = useApp();
  const [step, setStep] = useState(1);
  const [data, setData] = useState<WizardState>({
    skill: initialSkill,
    durationWeeks: 12,
    dailyMinutes: 30,
    experienceLevel: 'beginner',
    learningPreferences: [],
    goalStatement: '',
  });

  const handleNext = () => setStep(s => Math.min(s + 1, 4));
  const handleBack = () => setStep(s => Math.max(s - 1, 1));
  const updateData = (partial: Partial<WizardState>) => setData(d => ({ ...d, ...partial }));

  const handleGenerate = async () => {
    setStep(4); // Move to loading step
    try {
      const generated = await generateRoadmapFromPrompt(
        data.skill,
        data.durationWeeks,
        data.dailyMinutes,
        data.experienceLevel,
        data.learningPreferences,
        data.goalStatement
      );
      
      // Dispatch to context 
      // The context will assign an ID. Wait, I need to know the generated ID to redirect.
      // Context will generate uuidv4(). 
      // Instead, we can create the roadmap object here to know the ID, or fetch the latest.
      // Actually, since ADD_ROADMAP accepts Omit<Roadmap, 'id'>, we can't get the id easily if context generates it.
      // Wait, let's look at AppContext: ADD_ROADMAP creates `id: uuidv4()`.
      // I can just pass an ID to ADD_ROADMAP and ignore the Omit rule? No, it's typed.
      // Let me just navigate to `/roadmaps` after generation.
      
      dispatch({ type: 'ADD_ROADMAP', payload: generated });
      
      // Since we don't know the exact ID generated by context synchronously, 
      // we'll just redirect to the list view or assume it takes the top spot.
      setTimeout(() => {
        onComplete('new'); // We'll handle 'new' navigation logic in the parent
      }, 500);

    } catch (err) {
      console.error(err);
      handleBack(); // Error fallback
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        onClick={step < 4 ? onClose : undefined}
        className="absolute inset-0 bg-black/40 backdrop-blur-sm"
      />

      {/* Modal */}
      <motion.div
        layout
        initial={{ opacity: 0, scale: 0.95, y: 20 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.95, y: 20 }}
        transition={{ type: 'spring', damping: 25, stiffness: 300 }}
        className="relative w-full max-w-2xl bg-surface-primary rounded-[20px] shadow-xl overflow-hidden flex flex-col"
        style={{ minHeight: '500px', maxHeight: '90vh' }}
      >
        {/* Header & Progress Indicator (Hide during loading) */}
        {step < 4 && (
          <div className="flex items-center justify-between p-4 border-b border-border-primary">
            <div className="flex flex-col">
              <span className="text-xs font-semibold text-text-tertiary uppercase tracking-wider mb-1">
                Step {step} of 3
              </span>
              <div className="flex items-center gap-1.5">
                {[1, 2, 3].map((i) => (
                  <div key={i} className="flex items-center">
                    <div 
                      className={`h-2 rounded-full smooth-transition ${i === step ? 'w-8 bg-accent' : i < step ? 'w-4 bg-accent/50' : 'w-4 bg-surface-secondary'}`}
                    />
                  </div>
                ))}
              </div>
            </div>
            <button 
              onClick={onClose}
              className="p-2 rounded-full hover:bg-surface-secondary smooth-transition text-text-secondary"
            >
              <X className="h-5 w-5" />
            </button>
          </div>
        )}

        {/* Dynamic Content */}
        <div className="flex-1 overflow-y-auto p-6 lg:p-10 relative">
          <AnimatePresence mode="wait" initial={false}>
            {step === 1 && (
              <WizardStepSkill 
                key="step1" 
                data={data} 
                updateData={updateData} 
                onNext={handleNext} 
                onCancel={onClose} 
              />
            )}
            {step === 2 && (
              <WizardStepDuration 
                key="step2" 
                data={data} 
                updateData={updateData} 
                onNext={handleNext} 
                onBack={handleBack} 
              />
            )}
            {step === 3 && (
              <WizardStepPreferences 
                key="step3" 
                data={data} 
                updateData={updateData} 
                onSubmit={handleGenerate} 
                onBack={handleBack} 
              />
            )}
            {step === 4 && (
              <WizardStepLoading key="step4" />
            )}
          </AnimatePresence>
        </div>
      </motion.div>
    </div>
  );
}
